"""Recreate model board and card  migrations

Revision ID: 0ed5850f2c28
Revises: 4ce35f55279a
Create Date: 2026-01-05 17:53:39.989483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ed5850f2c28'
down_revision = '4ce35f55279a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('board', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('owner', sa.String(), nullable=False))
        batch_op.drop_column('message')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('board', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('owner')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
