"""changed name title to message in model

Revision ID: 981022e825e3
Revises: e2c888681db9
Create Date: 2025-12-21 17:14:01.436128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '981022e825e3'
down_revision = 'e2c888681db9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('board', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message', sa.String(), nullable=False))
        batch_op.drop_column('title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('board', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('message')

    # ### end Alembic commands ###
